server:
  port: 9001
spring:
  application:
    name: gateway-service
#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15 #多久没有收到心跳，会剔除服务 15s  （开发环境可以改，生产环境不要改）
    lease-renewal-interval-in-seconds: 5   #每一个服务多久向eureka发送一次心跳：5s （开发环境可以改，生产环境不要改

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    customer-service: #用户中心
      path: /customer/**
      serviceId: customer-service
#      strip-prefix: false #如果网关中的前缀与控制器的映射路径相同，只需要写一次
    user-service:
      path: /user/**   #员工用户中心
      serviceId: user-service
    auth-service:
      path: /auth/**
      serviceId: auth-service
    item-service: #后台微服务
      path: /item/**
      serviceId: item-service  #对应微服务的方式
     #如果网关中的前缀与控制器的映射路径相同，只需要写一次
    order-service:
      path: /order/**
      serviceId: order-service
    backstage-service:
      path: /backstage/**
      serviceId: backstage-service
      strip-prefix: false
  prefix: /api  #所有经过网关的请求，加上前
  add-host-header: true #经过网关调用微服务时，继续携带请求头中的域名  shopping.com
  sensitive-headers: #不用指定任何内容，覆盖原有配置，表示没有敏感关键字
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#配置jwt解析的相关信息，以及token的名称
#配置JWT需要的参数信息，不用硬编码在代码中
#insurance:
#  jwt:
#    #只需要保留需要的信息，解析只需要公钥以及cookieName即可
#    pubKeyPath: D:\\insurance_project\\tmp\\rsa.pub # 公钥地址
#    cookieName: insurance-token #cookie的名称
#  filter: #网关白名称，不拦截
#    allowPaths: #对应LoginProperies类中的属性名
#    - /api/auth
#    - /api/customer